package core

import (
	"bytes"
	"compress/zlib"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"sort"
	"strings"
)

var c2paMarkers = [][]byte{
	[]byte("c2pa"), []byte("C2PA"), []byte("jumb"), []byte("JUMB"), []byte("c2ma"),
	[]byte("contentcredentials"), []byte("contentauth"), []byte("cai:"),
	[]byte("http://ns.adobe.com/xmp/InstanceID/"),
}

var aiMetaHints = [][]byte{
	[]byte("c2pa"), []byte("C2PA"), []byte("contentcredentials"), []byte("ContentCredentials"),
	[]byte("digitalSourceType"), []byte("trainedAlgorithmicMedia"),
	[]byte("compositeWithTrainedAlgorithmicMedia"), []byte("algorithmicMedia"),
	[]byte("AIGC"), []byte("aigc"), []byte("AI generated"), []byte("Generated by"),
	[]byte("Claude"), []byte("Anthropic"), []byte("OpenAI"), []byte("SynthID"),
	[]byte("dcterms:provenance"),
}

var jpegCOMHints = [][]byte{
	[]byte("c2pa"), []byte("c2ma"), []byte("contentcredentials"), []byte("contentauth"),
	[]byte("cai:"), []byte("digitalSourceType"), []byte("trainedAlgorithmicMedia"),
	[]byte("compositeWithTrainedAlgorithmicMedia"), []byte("algorithmicMedia"),
	[]byte("AIGC"), []byte("AI generated"), []byte("Generated by AI"), []byte("SynthID"),
	[]byte("dcterms:provenance"),
}

var jpegC2PAMarkers = [][]byte{
	[]byte("c2pa"), []byte("c2ma"), []byte("contentcredentials"), []byte("contentauth"), []byte("cai:"),
}

var aiGeneratorProducts = []string{
	"ChatGPT", "DALL-E", "Midjourney", "Stable Diffusion", "SDXL", "FLUX", "DreamStudio",
	"Leonardo AI", "Leonardo.Ai", "Craiyon", "NovelAI", "Ideogram", "TensorArt", "Recraft",
	"Clipdrop", "DeepAI", "NightCafe", "Bing Image Creator", "Adobe Firefly", "Firefly", "Gemini",
	"Imagen", "Grok", "Sora", "Veo", "Kling", "Runway", "Luma", "Qwen", "GPT-4", "GPT-5",
}

var xmpUUID = []byte{0xbe, 0x7a, 0xcf, 0xcb, 0x97, 0xa9, 0x42, 0xe8, 0x9c, 0x71, 0x99, 0x94, 0x91, 0xe3, 0xaf, 0xac}
var c2paBMFFUUID = []byte{0xd8, 0xfe, 0xc3, 0xd6, 0x1b, 0x0e, 0x48, 0x3c, 0x92, 0x97, 0x58, 0x28, 0x87, 0x7e, 0xc4, 0x81}
var gifXMPApplicationID = []byte("XMP DataXMP")

var maxPNGTextDecompressedBytes = int64(1 << 20)

func containsAny(data []byte, markers [][]byte) []string {
	lower := bytes.ToLower(data)
	hits := make([]string, 0)
	for _, marker := range markers {
		name := string(marker)
		if bytes.Contains(lower, bytes.ToLower(marker)) {
			hits = append(hits, name)
		}
	}
	return hits
}

// blobMarkerHits mirrors the upstream container-level evidence shape. Image
// inspectors expose flat marker names, while document/SVG blob scans label
// provenance markers and AI hints separately so callers can distinguish the
// two kinds of evidence.
func blobMarkerHits(data []byte) (bool, bool, []string) {
	lower := bytes.ToLower(data)
	hits := make([]string, 0)
	hasC2PA, hasAI := false, false
	for _, marker := range c2paMarkers {
		if bytes.Contains(lower, bytes.ToLower(marker)) {
			hasC2PA = true
			hits = append(hits, "marker:"+string(marker))
		}
	}
	for _, hint := range aiMetaHints {
		if !bytes.Contains(lower, bytes.ToLower(hint)) {
			continue
		}
		hasAI = true
		label := string(hint)
		duplicate := false
		for _, finding := range hits {
			if strings.TrimPrefix(finding, "marker:") == label || strings.TrimPrefix(finding, "ai:") == label {
				duplicate = true
				break
			}
		}
		if !duplicate {
			hits = append(hits, "ai:"+label)
		}
	}
	if len(hits) > 30 {
		hits = hits[:30]
	}
	return hasC2PA, hasAI || hasC2PA, hits
}

func isC2PAHit(hits []string) bool {
	for _, hit := range hits {
		low := strings.ToLower(hit)
		if low == "c2pa" || low == "jumb" || low == "contentcredentials" || low == "contentauth" {
			return true
		}
	}
	return false
}

func inspectImage(data []byte, path string) FileReport {
	return inspectImageWithOptions(data, path, DefaultOptions(), true)
}

func inspectImageWithOptions(data []byte, path string, opts Options, runExternal bool) FileReport {
	return inspectImageWithSettings(data, path, opts, runExternal, runExternal, runExternal)
}

// inspectImageResidualWithOptions performs the post-clean image inspection.
// It retains the local c2patool verifier, but skips exiftool (its diagnostic
// dump is not part of the clean result) and skips SynthID unless the caller
// explicitly scores the changed pixels afterward.
func inspectImageResidualWithOptions(data []byte, path string, opts Options) FileReport {
	if opts.DisableExternalTools {
		return inspectImageWithSettings(data, path, opts, false, false, false)
	}
	return inspectImageWithSettings(data, path, opts, true, false, false)
}

func inspectImageWithSettings(data []byte, path string, opts Options, runTools, runSynthID, includeExiftool bool) FileReport {
	fmtName := detectImageFormat(data)
	var c2pa, ai bool
	var findings []string
	switch fmtName {
	case "png":
		c2pa, ai, findings = inspectPNG(data)
	case "jpeg":
		c2pa, ai, findings = inspectJPEG(data)
	case "webp":
		c2pa, ai, findings = inspectWebP(data)
	case "avif", "heic":
		c2pa, ai, findings = inspectISOBMFF(data, fmtName)
	case "bmp":
		c2pa, ai, findings = inspectBMP(data)
	case "gif":
		c2pa, ai, findings = inspectGIF(data)
	case "tiff":
		c2pa, ai, findings = inspectTIFF(data)
	default:
		findings = []string{"unsupported format (PNG/JPEG/WebP/AVIF/HEIC/BMP/GIF/TIFF)"}
	}
	report := FileReport{Kind: KindImage, Path: path, Format: fmtName, HasC2PA: c2pa, HasAIMetadata: ai, Findings: findings}
	if fmtName == "unknown" {
		report.Notes = []string{"format not fully inspected; only PNG/JPEG/WebP/AVIF/HEIC/BMP/GIF/TIFF are supported"}
	}
	if opts.DisableExternalTools {
		runTools = false
		runSynthID = false
	}
	if runTools {
		report.Tools = inspectOptionalToolsWithOptions(path, data, includeExiftool)
		if c2paTool, ok := report.Tools["c2patool"].(map[string]any); ok {
			if hasManifest, ok := c2paTool["has_manifest"].(bool); ok && hasManifest {
				report.HasC2PA = true
				report.Findings = append(report.Findings, "c2patool reports a C2PA-related manifest")
			}
			if available, ok := c2paTool["available"].(bool); ok && !available {
				report.Notes = append(report.Notes, "c2patool unavailable (not found); C2PA not fully inspected by this tool")
			} else if usable, ok := c2paTool["ok"].(bool); ok && !usable {
				detail, _ := c2paTool["error"].(string)
				if detail == "" {
					detail = "no usable verdict"
				}
				report.Notes = append(report.Notes, "c2patool probe inconclusive ("+detail+"); C2PA not fully inspected by this tool")
			}
		}
	}
	if runSynthID {
		report.SynthID = detectSynthIDForOptions(data, opts)
		if synthidIsWatermarked(report.SynthID) {
			suffix := ""
			if confidence, ok := report.SynthID["confidence"].(float64); ok {
				suffix = fmt.Sprintf(" (confidence=%.3f)", confidence)
			}
			report.Findings = append(report.Findings, "SynthID pixel watermark detected"+suffix)
		} else if report.SynthID != nil {
			if detail, ok := report.SynthID["error"].(string); ok && detail != "" {
				report.Findings = append(report.Findings, "SynthID scorer inconclusive: "+detail)
			}
		}
	}
	for _, f := range report.Findings {
		report.FindingsConfidence = append(report.FindingsConfidence, findingConfidence(f))
	}
	return report
}

func findingConfidence(f string) string {
	l := strings.ToLower(f)
	// Match the upstream audit buckets: a parsed provenance structure is
	// stronger than a vendor string found inside ordinary metadata, while
	// parser notes and common typography are not actionable evidence.
	if strings.HasPrefix(l, "layer-a") && strings.HasSuffix(l, "(space)") {
		return "informational"
	}
	if strings.Contains(l, "c2patool reports") ||
		strings.Contains(l, "c2pa-related manifest") ||
		strings.Contains(l, "png chunk c2") ||
		strings.Contains(l, "png chunk cabx") ||
		strings.Contains(l, "png chunk jumb") ||
		strings.Contains(l, "png chunk jumd") ||
		strings.Contains(l, "jpeg app11 segment") ||
		strings.Contains(l, "digital_source_type") ||
		strings.Contains(l, "digitalsourcetype") ||
		strings.Contains(l, "trainedalgorithmicmedia") ||
		strings.Contains(l, "compositewithtrainedalgorithmicmedia") ||
		strings.Contains(l, "softwareagent") {
		return "confirmed"
	}
	if strings.HasPrefix(l, "info:") ||
		strings.Contains(l, "cms generator") ||
		strings.Contains(l, "customxml parts") ||
		strings.Contains(l, "xmp packet present") ||
		strings.Contains(l, "unsupported") ||
		strings.Contains(l, "not fully inspected") ||
		strings.Contains(l, "format not") ||
		strings.Contains(l, "svg <metadata> present") ||
		strings.Contains(l, "not a valid") ||
		strings.Contains(l, "partial read") ||
		strings.Contains(l, "truncated chunk") ||
		strings.Contains(l, "bad segment length") ||
		strings.Contains(l, "svg decode note") ||
		strings.Contains(l, "truncated") {
		return "informational"
	}
	if strings.Contains(l, "byte-scan") {
		return "likely_false_positive"
	}
	if strings.Contains(l, "ai:") ||
		strings.Contains(l, "marker:") ||
		strings.Contains(l, "meta:") ||
		strings.Contains(l, "frontmatter") ||
		strings.Contains(l, "json-ld") ||
		strings.Contains(l, "attr:") ||
		strings.Contains(l, "png ") ||
		strings.Contains(l, "jpeg app") ||
		strings.Contains(l, "exif") ||
		strings.Contains(l, "xmp") ||
		strings.Contains(l, "interesting") ||
		strings.Contains(l, "pdf-structured") ||
		strings.Contains(l, "layer-a") {
		return "probable"
	}
	return "informational"
}

func cleanImage(data []byte, format string, opts Options) ([]byte, []string, error) {
	stripAll := stripAllMetadata(opts)
	var out []byte
	var actions []string
	var err error
	switch format {
	case "png":
		out, actions = stripPNG(data, stripAll)
	case "jpeg":
		out, actions = stripJPEG(data, stripAll)
	case "webp":
		out, actions = stripWebP(data, stripAll)
		if len(actions) > 0 && strings.HasPrefix(actions[0], "malformed WebP:") {
			err = fmt.Errorf("%s", actions[0])
		}
	case "avif", "heic":
		out, actions, err = stripISOBMFF(data, format, stripAll)
	case "bmp":
		out, actions = stripBMP(data, stripAll)
	case "gif":
		out, actions = stripGIF(data, stripAll)
	case "tiff":
		if info, valid := tiffLayout(data); !valid || len(collectTIFFIFDs(data, info)) == 0 {
			err = errors.New("not a valid TIFF (no image file directories)")
		} else {
			out, actions = stripTIFF(data, stripAll)
		}
	default:
		err = fmt.Errorf("unsupported image format: %s", format)
	}
	return out, actions, err
}

func inspectPNG(data []byte) (bool, bool, []string) {
	if !bytes.HasPrefix(data, []byte{0x89, 'P', 'N', 'G', 0x0d, 0x0a, 0x1a, 0x0a}) {
		return false, false, []string{"not a PNG"}
	}
	var c2pa, ai bool
	findings := []string{}
	for pos := 8; pos+8 <= len(data); {
		length := int(binary.BigEndian.Uint32(data[pos : pos+4]))
		if length < 0 || pos+12+length > len(data) {
			findings = append(findings, fmt.Sprintf("truncated chunk %q", data[pos+4:minInt(pos+8, len(data))]))
			break
		}
		ctype := data[pos+4 : pos+8]
		payload := data[pos+8 : pos+8+length]
		name := string(ctype)
		if bytes.Equal(ctype, []byte("caBX")) || bytes.Equal(ctype, []byte("juMB")) || bytes.Equal(ctype, []byte("jumb")) || bytes.HasPrefix(ctype, []byte("c2")) {
			c2pa, ai = true, true
			findings = append(findings, "PNG chunk "+name+" (possible C2PA container)")
		}
		if bytes.Equal(ctype, []byte("tEXt")) || bytes.Equal(ctype, []byte("zTXt")) || bytes.Equal(ctype, []byte("iTXt")) || bytes.Equal(ctype, []byte("eXIf")) {
			decoded, exceeded := pngTextPayloadCapped(payload, ctype)
			if exceeded {
				findings = append(findings, fmt.Sprintf("PNG %s: not fully inspected (decompressed text exceeds cap)", name))
			} else {
				blob := make([]byte, 0, len(payload)+1+len(decoded))
				blob = append(blob, payload...)
				blob = append(blob, '\n')
				blob = append(blob, decoded...)
				hits := containsAny(blob, append(aiMetaHints, c2paMarkers...))
				products := pngGeneratorHits(payload, ctype)
				if len(hits) > 0 || len(products) > 0 {
					ai = true
					if isC2PAHit(hits) {
						c2pa = true
					}
					parts := make([]string, 0, 2)
					if len(hits) > 0 {
						parts = append(parts, strings.Join(hits[:minInt(8, len(hits))], ", "))
					}
					if len(products) > 0 {
						parts = append(parts, "AI generator ("+strings.Join(products[:minInt(8, len(products))], ", ")+")")
					}
					findings = append(findings, "PNG "+name+": "+strings.Join(parts, "; "))
				}
			}
		}
		pos += 12 + length
		if bytes.Equal(ctype, []byte("IEND")) {
			break
		}
	}
	whole := containsAny(data, c2paMarkers)
	if len(whole) > 0 && !c2pa {
		c2pa, ai = true, true
		findings = append(findings, "byte-scan C2PA markers: "+strings.Join(whole[:minInt(6, len(whole))], ", "))
	}
	return c2pa, ai || c2pa, findings
}

func pngTextPayload(payload, ctype []byte) []byte {
	decoded, _ := pngTextPayloadCapped(payload, ctype)
	return decoded
}

func pngTextPayloadCapped(payload, ctype []byte) ([]byte, bool) {
	switch string(ctype) {
	case "tEXt":
		if i := bytes.IndexByte(payload, 0); i >= 0 {
			return payload[i+1:], false
		}
		return payload, false
	case "zTXt":
		if i := bytes.IndexByte(payload, 0); i >= 0 && i+2 <= len(payload) {
			z, err := zlib.NewReader(bytes.NewReader(payload[i+2:]))
			if err == nil {
				b, readErr := io.ReadAll(io.LimitReader(z, maxPNGTextDecompressedBytes+1))
				z.Close()
				if int64(len(b)) > maxPNGTextDecompressedBytes {
					return nil, true
				}
				if readErr == nil {
					return b, false
				}
			}
		}
	case "iTXt":
		if i := bytes.IndexByte(payload, 0); i >= 0 && i+3 < len(payload) {
			rest := payload[i+1:]
			compressed := rest[0] == 1
			rest = rest[2:]
			if j := bytes.IndexByte(rest, 0); j >= 0 {
				rest = rest[j+1:]
			}
			if j := bytes.IndexByte(rest, 0); j >= 0 {
				rest = rest[j+1:]
			}
			if compressed {
				z, err := zlib.NewReader(bytes.NewReader(rest))
				if err == nil {
					b, e := io.ReadAll(io.LimitReader(z, maxPNGTextDecompressedBytes+1))
					z.Close()
					if int64(len(b)) > maxPNGTextDecompressedBytes {
						return nil, true
					}
					if e == nil {
						return b, false
					}
				}
			}
			return rest, false
		}
	}
	return payload, false
}

func pngGeneratorHits(payload, ctype []byte) []string {
	if !(bytes.Equal(ctype, []byte("tEXt")) || bytes.Equal(ctype, []byte("zTXt")) || bytes.Equal(ctype, []byte("iTXt"))) {
		return nil
	}
	key := payload
	if i := bytes.IndexByte(key, 0); i >= 0 {
		key = key[:i]
	}
	lowerKey := strings.ToLower(string(key))
	if lowerKey != "software" && lowerKey != "creator" && lowerKey != "parameters" {
		return nil
	}
	value := strings.ToLower(string(pngTextPayload(payload, ctype)))
	var hits []string
	for _, product := range aiGeneratorProducts {
		if strings.Contains(value, strings.ToLower(product)) {
			hits = append(hits, string(key)+"="+product)
		}
	}
	return hits
}

func pngChunk(ctype, payload []byte) []byte {
	out := make([]byte, 0, len(payload)+12)
	var n [4]byte
	binary.BigEndian.PutUint32(n[:], uint32(len(payload)))
	out = append(out, n[:]...)
	out = append(out, ctype...)
	out = append(out, payload...)
	crc := crc32IEEE(append(append([]byte(nil), ctype...), payload...))
	binary.BigEndian.PutUint32(n[:], crc)
	out = append(out, n[:]...)
	return out
}

func crc32IEEE(data []byte) uint32 {
	// A small local implementation avoids making the metadata path depend on
	// image encoders; the polynomial is the PNG/IEEE CRC-32 polynomial.
	var table [256]uint32
	for i := range table {
		c := uint32(i)
		for j := 0; j < 8; j++ {
			if c&1 != 0 {
				c = 0xedb88320 ^ c>>1
			} else {
				c >>= 1
			}
		}
		table[i] = c
	}
	crc := uint32(0xffffffff)
	for _, b := range data {
		crc = table[byte(crc)^b] ^ crc>>8
	}
	return ^crc
}

func stripPNG(data []byte, stripAll bool) ([]byte, []string) {
	if !bytes.HasPrefix(data, []byte{0x89, 'P', 'N', 'G', 0x0d, 0x0a, 0x1a, 0x0a}) {
		return data, []string{"not PNG"}
	}
	out := append([]byte(nil), data[:8]...)
	actions := []string{}
	for pos := 8; pos+8 <= len(data); {
		length := int(binary.BigEndian.Uint32(data[pos : pos+4]))
		ctype := data[pos+4 : minInt(pos+8, len(data))]
		if length < 0 || pos+12+length > len(data) {
			out = append(out, data[pos:]...)
			actions = append(actions, fmt.Sprintf("kept %d bytes of truncated chunk %s tail (file truncated)", len(data)-pos, string(ctype)))
			break
		}
		payload := data[pos+8 : pos+8+length]
		chunkEnd := pos + 12 + length
		drop := false
		decompressionExceeded := false
		name := string(ctype)
		low := strings.ToLower(name)
		if bytes.Equal(ctype, []byte("eXIf")) || bytes.Equal(ctype, []byte("caBX")) || bytes.HasPrefix(ctype, []byte("c2")) || strings.Contains(low, "jumb") {
			drop = true
		} else if bytes.Equal(ctype, []byte("tEXt")) || bytes.Equal(ctype, []byte("zTXt")) || bytes.Equal(ctype, []byte("iTXt")) {
			decoded, exceeded := pngTextPayloadCapped(payload, ctype)
			if exceeded {
				drop = true
				decompressionExceeded = true
			} else {
				blob := make([]byte, 0, len(payload)+1+len(decoded))
				blob = append(blob, payload...)
				blob = append(blob, '\n')
				blob = append(blob, decoded...)
				drop = stripAll || len(containsAny(blob, append(aiMetaHints, c2paMarkers...))) > 0 || len(pngGeneratorHits(payload, ctype)) > 0
			}
		} else if len(containsAny(append(append([]byte(nil), ctype...), payload...), c2paMarkers)) > 0 && !bytes.Equal(ctype, []byte("IHDR")) && !bytes.Equal(ctype, []byte("IDAT")) && !bytes.Equal(ctype, []byte("IEND")) && !bytes.Equal(ctype, []byte("PLTE")) && !bytes.Equal(ctype, []byte("tRNS")) && !bytes.Equal(ctype, []byte("gAMA")) && !bytes.Equal(ctype, []byte("pHYs")) && !bytes.Equal(ctype, []byte("sRGB")) && !bytes.Equal(ctype, []byte("cHRM")) && !bytes.Equal(ctype, []byte("iCCP")) {
			drop = true
		}
		if drop {
			if decompressionExceeded {
				actions = append(actions, fmt.Sprintf("drop chunk %s (decompressed text exceeds cap)", name))
			} else {
				actions = append(actions, "drop chunk "+name)
			}
		} else {
			out = append(out, data[pos:chunkEnd]...)
		}
		pos = chunkEnd
		if bytes.Equal(ctype, []byte("IEND")) {
			break
		}
	}
	if len(actions) == 0 {
		actions = append(actions, "no PNG metadata chunks removed (already clean or none matched)")
	}
	return out, actions
}

func inspectJPEG(data []byte) (bool, bool, []string) {
	if len(data) < 2 || data[0] != 0xff || data[1] != 0xd8 {
		return false, false, []string{"not JPEG"}
	}
	var c2pa, ai bool
	findings := []string{}
	i := 2
	for i < len(data) {
		if data[i] != 0xff {
			i++
			continue
		}
		for i < len(data) && data[i] == 0xff {
			i++
		}
		if i >= len(data) {
			break
		}
		marker := data[i]
		i++
		if marker == 0xda {
			break
		}
		if marker == 0xd9 {
			continue
		}
		if marker == 0xd8 || marker >= 0xd0 && marker <= 0xd7 {
			continue
		}
		if i+2 > len(data) {
			break
		}
		segLen := int(binary.BigEndian.Uint16(data[i : i+2]))
		if segLen < 2 || i+segLen > len(data) {
			findings = append(findings, fmt.Sprintf("bad segment length at marker 0x%02X", marker))
			break
		}
		payload := data[i+2 : i+segLen]
		if marker == 0xeb {
			c2pa, ai = true, true
			findings = append(findings, "JPEG APP11 segment (JUMBF/C2PA common)")
		}
		if marker == 0xe1 || marker == 0xe2 || marker == 0xed || marker == 0xee || marker == 0xeb {
			hits := containsAny(payload, append(aiMetaHints, c2paMarkers...))
			if len(hits) > 0 {
				ai = true
				if isC2PAHit(hits) {
					c2pa = true
				}
				findings = append(findings, fmt.Sprintf("JPEG APP%d: %s", marker-0xe0, strings.Join(hits[:minInt(8, len(hits))], ", ")))
			}
		}
		if marker == 0xfe {
			hits := containsAny(payload, jpegCOMHints)
			if len(hits) > 0 {
				ai = true
				if isC2PAHit(hits) {
					c2pa = true
				}
				findings = append(findings, "JPEG COM: "+strings.Join(hits[:minInt(8, len(hits))], ", "))
			}
		}
		i += segLen
	}
	whole := containsAny(data, jpegC2PAMarkers)
	if len(whole) > 0 && !c2pa {
		c2pa, ai = true, true
		findings = append(findings, "byte-scan C2PA markers: "+strings.Join(whole[:minInt(6, len(whole))], ", "))
	}
	return c2pa, ai || c2pa, findings
}

func stripJPEG(data []byte, stripAll bool) ([]byte, []string) {
	if len(data) < 2 || data[0] != 0xff || data[1] != 0xd8 {
		return data, []string{"not JPEG"}
	}
	out := append([]byte(nil), data[:2]...)
	actions := []string{}
	i := 2
	for i < len(data) {
		if data[i] != 0xff {
			out = append(out, data[i:]...)
			actions = append(actions, "copied remainder after non-marker byte")
			break
		}
		for i < len(data) && data[i] == 0xff {
			i++
		}
		if i >= len(data) {
			break
		}
		marker := data[i]
		i++
		if marker == 0xd9 {
			out = append(out, 0xff, 0xd9)
			break
		}
		if marker == 0xd8 {
			continue
		}
		if marker >= 0xd0 && marker <= 0xd7 {
			out = append(out, 0xff, marker)
			continue
		}
		if marker == 0xda {
			if i+2 > len(data) {
				break
			}
			out = append(out, 0xff, marker)
			out = append(out, data[i:]...)
			actions = append(actions, "preserved entropy-coded scan (SOS→EOF)")
			break
		}
		if i+2 > len(data) {
			out = append(out, 0xff, marker)
			out = append(out, data[i:]...)
			break
		}
		segLen := int(binary.BigEndian.Uint16(data[i : i+2]))
		if segLen < 2 || i+segLen > len(data) {
			out = append(out, 0xff, marker)
			out = append(out, data[i:]...)
			actions = append(actions, "kept truncated JPEG segment tail")
			break
		}
		payload := data[i+2 : i+segLen]
		drop := false
		if marker == 0xeb {
			drop = true
			actions = append(actions, "drop APP11 (C2PA/JUMBF)")
		} else if marker >= 0xe0 && marker <= 0xef {
			if stripAll && marker != 0xe0 {
				drop = true
				actions = append(actions, fmt.Sprintf("drop APP%d", marker-0xe0))
			} else if len(containsAny(payload, append(aiMetaHints, c2paMarkers...))) > 0 {
				drop = true
				actions = append(actions, fmt.Sprintf("drop APP%d (AI/C2PA markers)", marker-0xe0))
			}
		} else if marker == 0xfe {
			if stripAll || len(containsAny(payload, jpegCOMHints)) > 0 {
				drop = true
				actions = append(actions, "drop COM comment")
			}
		}
		if !drop {
			out = append(out, 0xff, marker)
			out = append(out, data[i:i+segLen]...)
		}
		i += segLen
	}
	if len(actions) == 0 {
		actions = append(actions, "no JPEG APP segments removed")
	}
	return out, actions
}

type webpChunk struct {
	fourcc  []byte
	payload []byte
	padding []byte
}

func parseWebP(data []byte) ([]webpChunk, []string) {
	if len(data) < 12 || !bytes.Equal(data[:4], []byte("RIFF")) || !bytes.Equal(data[8:12], []byte("WEBP")) {
		return nil, []string{"not a WebP"}
	}
	chunks := []webpChunk{}
	notes := []string{}
	declaredSize := binary.LittleEndian.Uint32(data[4:8])
	if int64(declaredSize)+8 != int64(len(data)) {
		notes = append(notes, fmt.Sprintf("RIFF size mismatch: header=%d actual=%d", int64(declaredSize)+8, len(data)))
	}
	pos := 12
	for pos+8 <= len(data) {
		size := int(binary.LittleEndian.Uint32(data[pos+4 : pos+8]))
		end := pos + 8 + size
		if end > len(data) {
			notes = append(notes, fmt.Sprintf("truncated WebP chunk %s", string(data[pos:pos+4])))
			break
		}
		padEnd := end
		if size&1 != 0 {
			padEnd++
		}
		if padEnd > len(data) {
			notes = append(notes, "truncated WebP chunk padding")
			break
		}
		chunks = append(chunks, webpChunk{append([]byte(nil), data[pos:pos+4]...), data[pos+8 : end], data[end:padEnd]})
		pos = padEnd
	}
	truncated := false
	for _, note := range notes {
		if strings.Contains(strings.ToLower(note), "truncated") {
			truncated = true
			break
		}
	}
	if pos != len(data) && !truncated {
		notes = append(notes, fmt.Sprintf("trailing WebP bytes: %d", len(data)-pos))
	}
	return chunks, notes
}

func inspectWebP(data []byte) (bool, bool, []string) {
	chunks, notes := parseWebP(data)
	if len(chunks) == 0 && len(notes) == 1 && notes[0] == "not a WebP" {
		return false, false, notes
	}
	findings := append([]string(nil), notes...)
	var c2pa, ai bool
	for _, c := range chunks {
		name := string(c.fourcc)
		if strings.EqualFold(name, "C2PA") {
			c2pa, ai = true, true
			findings = append(findings, "WebP C2PA chunk")
			continue
		}
		if name == "XMP " || name == "EXIF" {
			hits := containsAny(c.payload, append(aiMetaHints, c2paMarkers...))
			if len(hits) > 0 {
				ai = true
				if isC2PAHit(hits) {
					c2pa = true
				}
				findings = append(findings, "WebP "+name+": "+strings.Join(hits[:minInt(8, len(hits))], ", "))
			}
		}
	}
	return c2pa, ai || c2pa, findings
}

func stripWebP(data []byte, stripAll bool) ([]byte, []string) {
	chunks, notes := parseWebP(data)
	if len(chunks) == 0 && len(notes) == 1 && notes[0] == "not a WebP" {
		return data, notes
	}
	if len(notes) > 0 {
		return data, append([]string{"malformed WebP: " + strings.Join(notes, "; ")}, notes...)
	}
	kept := []webpChunk{}
	removedFlags := byte(0)
	actions := []string{}
	for _, c := range chunks {
		name := string(c.fourcc)
		drop := strings.EqualFold(name, "C2PA")
		flag := byte(0)
		switch name {
		case "ICCP":
			flag = 0x20
		case "EXIF":
			flag = 0x08
		case "XMP ":
			flag = 0x04
		}
		if flag != 0 && (stripAll || len(containsAny(c.payload, append(aiMetaHints, c2paMarkers...))) > 0) {
			drop = true
			removedFlags |= flag
		}
		if drop {
			actions = append(actions, "drop WebP chunk "+name)
			continue
		}
		kept = append(kept, c)
	}
	body := []byte("WEBP")
	for _, c := range kept {
		payload := c.payload
		if string(c.fourcc) == "VP8X" && len(payload) >= 1 && removedFlags != 0 {
			payload = append([]byte(nil), payload...)
			payload[0] &^= removedFlags
		}
		var n [4]byte
		body = append(body, c.fourcc...)
		binary.LittleEndian.PutUint32(n[:], uint32(len(payload)))
		body = append(body, n[:]...)
		body = append(body, payload...)
		if len(payload)&1 != 0 {
			if len(c.padding) > 0 {
				body = append(body, c.padding...)
			} else {
				body = append(body, 0)
			}
		}
	}
	out := append([]byte("RIFF"), make([]byte, 4)...)
	binary.LittleEndian.PutUint32(out[4:8], uint32(len(body)))
	out = append(out, body...)
	if len(actions) == 0 {
		actions = append(actions, "no WebP metadata chunks removed (already clean or none matched)")
	}
	return out, actions
}

func bmpPayloadExtent(data []byte) (int, int, bool) {
	if len(data) < 30 || !bytes.HasPrefix(data, []byte("BM")) {
		return 0, 0, false
	}
	off := int(binary.LittleEndian.Uint32(data[10:14]))
	dib := int(binary.LittleEndian.Uint32(data[14:18]))
	if dib < 40 || dib > len(data)-14 || off > len(data) {
		return 0, 0, false
	}
	w := int64(int32(binary.LittleEndian.Uint32(data[18:22])))
	h := int64(int32(binary.LittleEndian.Uint32(data[22:26])))
	bpp := int64(binary.LittleEndian.Uint16(data[28:30]))
	if w <= 0 || bpp == 0 {
		return 0, 0, false
	}
	if h < 0 {
		h = -h
	}
	var size64 int64
	compression := binary.LittleEndian.Uint32(data[30:34])
	if compression == 0 {
		row := ((w*bpp + 31) / 32) * 4
		const maxInt64 = int64(^uint64(0) >> 1)
		if h != 0 && row > maxInt64/h {
			return 0, 0, false
		}
		size64 = row * h
	} else {
		size64 = int64(binary.LittleEndian.Uint32(data[34:38]))
		if size64 == 0 {
			return 0, 0, false
		}
	}
	const maxInt = int64(^uint(0) >> 1)
	if size64 < 0 || size64 > maxInt {
		return 0, 0, false
	}
	// Keep a declared payload that extends beyond EOF as a valid extent. The
	// upstream inspector treats this as a truncated/header-only BMP and avoids
	// scanning the incomplete raster for metadata.
	return off, int(size64), true
}

func inspectBMP(data []byte) (bool, bool, []string) {
	if len(data) < 14 || !bytes.HasPrefix(data, []byte("BM")) {
		return false, false, []string{"not a BMP"}
	}
	off, size, ok := bmpPayloadExtent(data)
	if !ok {
		return false, false, []string{"BMP header not fully parsed"}
	}
	if off > len(data) || size > len(data)-off {
		return false, false, []string{"BMP has no metadata (header-only raster format)"}
	}
	end := off + size
	if end >= len(data) {
		return false, false, []string{"BMP has no metadata (header-only raster format)"}
	}
	hits := containsAny(data[end:], append(aiMetaHints, c2paMarkers...))
	if len(hits) == 0 {
		return false, false, []string{fmt.Sprintf("BMP has %d unrecognized trailing byte(s)", len(data)-end)}
	}
	return isC2PAHit(hits), true, []string{"BMP trailing metadata: " + strings.Join(hits[:minInt(6, len(hits))], ", ")}
}

func stripBMP(data []byte, stripAll bool) ([]byte, []string) {
	off, size, ok := bmpPayloadExtent(data)
	if !ok {
		return data, []string{"BMP header not fully parsed; left unchanged"}
	}
	if off > len(data) || size > len(data)-off {
		return data, []string{"no BMP trailing metadata to strip"}
	}
	end := off + size
	if end >= len(data) {
		return data, []string{"no BMP trailing metadata to strip"}
	}
	trailing := data[end:]
	hits := containsAny(trailing, append(aiMetaHints, c2paMarkers...))
	if !stripAll && len(hits) == 0 {
		return data, []string{"BMP trailing bytes kept (keep-non-ai-metadata)"}
	}
	out := append([]byte(nil), data[:end]...)
	binary.LittleEndian.PutUint32(out[2:6], uint32(end))
	reason := ""
	if len(hits) > 0 {
		reason = " (" + strings.Join(hits[:minInt(4, len(hits))], ", ") + ")"
	}
	return out, []string{fmt.Sprintf("drop %d BMP trailing byte(s)%s", len(trailing), reason)}
}

func gifSubBlocks(data []byte, pos int) (int, []byte, bool) {
	var payload []byte
	for pos < len(data) {
		size := int(data[pos])
		pos++
		if size == 0 {
			return pos, payload, true
		}
		if pos+size > len(data) {
			return pos, payload, false
		}
		payload = append(payload, data[pos:pos+size]...)
		pos += size
	}
	return pos, payload, false
}

func inspectGIF(data []byte) (bool, bool, []string) {
	if len(data) < 6 || !(bytes.HasPrefix(data, []byte("GIF87a")) || bytes.HasPrefix(data, []byte("GIF89a"))) {
		return false, false, []string{"not a GIF"}
	}
	findings := []string{}
	if len(data) < 13 {
		return false, false, []string{"truncated GIF header"}
	}
	pos := 6
	packed := data[pos+4]
	pos += 7
	if packed&0x80 != 0 {
		pos += 3 * (1 << ((packed & 7) + 1))
	}
	var c2pa, ai bool
	for pos < len(data) {
		switch data[pos] {
		case 0x3b:
			pos = len(data)
		case 0x2c:
			if pos+10 > len(data) {
				findings = append(findings, "truncated GIF image block")
				pos = len(data)
				continue
			}
			packed := data[pos+9]
			pos += 10
			if packed&0x80 != 0 {
				pos += 3 * (1 << ((packed & 7) + 1))
			}
			if pos >= len(data) {
				findings = append(findings, "truncated GIF image block")
				continue
			}
			pos++
			var valid bool
			pos, _, valid = gifSubBlocks(data, pos)
			if !valid {
				findings = append(findings, "truncated GIF image block")
				continue
			}
		case 0x21:
			if pos+2 > len(data) {
				findings = append(findings, "truncated GIF extension")
				pos = len(data)
				continue
			}
			label := data[pos+1]
			pos += 2
			var payload []byte
			var valid bool
			pos, payload, valid = gifSubBlocks(data, pos)
			if !valid {
				findings = append(findings, "truncated GIF extension")
				continue
			}
			if label == 0xfe {
				findings = append(findings, "GIF comment extension present")
				hits := containsAny(payload, append(aiMetaHints, c2paMarkers...))
				if len(hits) > 0 {
					ai = true
					findings = append(findings, "GIF comment: "+strings.Join(hits[:minInt(6, len(hits))], ", "))
				}
			}
			if label == 0xff {
				ident := payload
				if len(ident) > len(gifXMPApplicationID) {
					ident = ident[:len(gifXMPApplicationID)]
				}
				if bytes.Equal(ident, gifXMPApplicationID) {
					findings = append(findings, "GIF XMP application extension present")
					hits := containsAny(payload, append(aiMetaHints, c2paMarkers...))
					if len(hits) > 0 {
						ai = true
						if isC2PAHit(hits) {
							c2pa = true
						}
						findings = append(findings, "GIF XMP: "+strings.Join(hits[:minInt(6, len(hits))], ", "))
					}
				} else if len(ident) >= 4 && (bytes.Contains(ident, []byte("c2pa")) || bytes.Contains(ident, []byte("jumb")) || bytes.Contains(ident, []byte("C2PA")) || bytes.Contains(ident, []byte("JUMB"))) {
					c2pa = true
					findings = append(findings, "GIF application extension (possible C2PA)")
				}
			}
		default:
			pos++
		}
	}
	if whole := containsAny(data, c2paMarkers); len(whole) > 0 && !c2pa {
		c2pa = true
		findings = append(findings, "byte-scan C2PA markers: "+strings.Join(whole[:minInt(6, len(whole))], ", "))
	}
	if len(findings) == 0 {
		findings = append(findings, "no GIF metadata extensions found")
	}
	return c2pa, ai || c2pa, findings
}

func stripGIF(data []byte, stripAll bool) ([]byte, []string) {
	if len(data) < 6 || !(bytes.HasPrefix(data, []byte("GIF87a")) || bytes.HasPrefix(data, []byte("GIF89a"))) {
		return data, []string{"not GIF"}
	}
	if len(data) < 13 {
		return data, []string{"truncated GIF header"}
	}
	pos := 6
	packed := data[pos+4]
	pos += 7
	out := append([]byte(nil), data[:pos]...)
	if packed&0x80 != 0 {
		gctSize := 3 * (1 << ((packed & 7) + 1))
		out = append(out, data[pos:minInt(pos+gctSize, len(data))]...)
		pos += gctSize
	}
	actions := []string{}
	for pos < len(data) {
		start := pos
		switch data[pos] {
		case 0x3b:
			out = append(out, data[pos:]...)
			pos = len(data)
		case 0x2c:
			if pos+10 > len(data) {
				out = append(out, data[pos:]...)
				pos = len(data)
				actions = append(actions, "kept truncated GIF image tail")
				continue
			}
			packed := data[pos+9]
			pos += 10
			if packed&0x80 != 0 {
				pos += 3 * (1 << ((packed & 7) + 1))
			}
			if pos >= len(data) {
				out = append(out, data[start:]...)
				pos = len(data)
				continue
			}
			pos++
			var valid bool
			pos, _, valid = gifSubBlocks(data, pos)
			if !valid {
				out = append(out, data[start:]...)
				pos = len(data)
				actions = append(actions, "kept truncated GIF image tail")
				continue
			}
			out = append(out, data[start:pos]...)
		case 0x21:
			if pos+2 > len(data) {
				out = append(out, data[pos:]...)
				pos = len(data)
				continue
			}
			label := data[pos+1]
			pos += 2
			var payload []byte
			var valid bool
			pos, payload, valid = gifSubBlocks(data, pos)
			if !valid {
				out = append(out, data[start:]...)
				pos = len(data)
				actions = append(actions, "kept truncated GIF extension tail")
				continue
			}
			drop := false
			if label == 0xfe {
				drop = stripAll || len(containsAny(payload, append(aiMetaHints, c2paMarkers...))) > 0
				if drop {
					actions = append(actions, "drop GIF comment extension")
				}
			}
			if label == 0xff {
				ident := payload
				if len(ident) > 11 {
					ident = ident[:11]
				}
				hits := containsAny(payload, append(aiMetaHints, c2paMarkers...))
				switch {
				case bytes.Equal(ident, gifXMPApplicationID):
					drop = stripAll || len(hits) > 0
					if drop {
						actions = append(actions, "drop GIF XMP application extension")
					}
				case bytes.Equal(ident, []byte("NETSCAPE2.0")) || bytes.Equal(ident, []byte("ICCRGBG1012")):
					drop = len(hits) > 0
					if drop {
						actions = append(actions, "drop GIF control application extension")
					}
				default:
					drop = stripAll || len(hits) > 0
					if drop {
						actions = append(actions, "drop GIF application extension")
					}
				}
			}
			if !drop {
				out = append(out, data[start:pos]...)
			}
		default:
			out = append(out, data[pos:]...)
			pos = len(data)
		}
	}
	if len(actions) == 0 {
		actions = append(actions, "no GIF metadata blocks removed (already clean or none matched)")
	}
	return out, actions
}

var tiffMetadataTags = map[uint16]string{
	269: "DocumentName", 270: "ImageDescription", 271: "Make", 272: "Model", 305: "Software", 306: "DateTime", 315: "Artist", 316: "HostComputer", 33432: "Copyright", 40091: "XPTitle", 40092: "XPComment", 40093: "XPAuthor", 40094: "XPKeywords", 40095: "XPSubject", 700: "XMP", 33723: "IPTC/NAA", 34377: "Photoshop", 34665: "ExifIFD", 34853: "GPSInfo", 37500: "MakerNote",
}

var tiffStructuralTags = map[uint16]bool{
	254: true, 255: true, 256: true, 257: true, 258: true, 259: true, 262: true,
	263: true, 264: true, 265: true, 266: true, 273: true, 274: true, 277: true,
	278: true, 279: true, 282: true, 283: true, 284: true, 285: true, 286: true,
	287: true, 288: true, 289: true, 290: true, 291: true, 292: true, 293: true,
	294: true, 295: true, 296: true, 297: true, 301: true, 302: true, 304: true,
	320: true, 321: true, 322: true, 323: true, 324: true, 325: true, 326: true,
	327: true, 328: true, 329: true, 330: true, 331: true, 332: true, 333: true,
	334: true, 336: true, 338: true, 339: true, 340: true, 341: true, 342: true,
	343: true, 344: true, 345: true, 346: true, 347: true, 512: true, 513: true,
	514: true, 515: true, 516: true, 517: true, 518: true, 519: true, 520: true,
	521: true, 529: true, 530: true,
	531: true, 532: true, 533: true, 33421: true, 33422: true, 33423: true,
	34675: true, 34676: true,
}

func init() {
	for tag := uint16(50706); tag <= 50741; tag++ {
		tiffStructuralTags[tag] = true
	}
}

type tiffInfo struct {
	little, big                                    bool
	first                                          uint64
	countBytes, offsetBytes, entrySize, headerSize int
}

func tiffLayout(data []byte) (tiffInfo, bool) {
	if len(data) < 4 {
		return tiffInfo{}, false
	}
	little := bytes.Equal(data[:2], []byte("II"))
	bigEndian := bytes.Equal(data[:2], []byte("MM"))
	if !little && !bigEndian {
		return tiffInfo{}, false
	}
	var order binary.ByteOrder
	if bigEndian {
		order = binary.BigEndian
	} else {
		order = binary.LittleEndian
	}
	version := order.Uint16(data[2:4])
	if version == 42 {
		info := tiffInfo{little: little, countBytes: 2, offsetBytes: 4, entrySize: 12, headerSize: 8}
		if len(data) >= info.headerSize {
			info.first = uint64(order.Uint32(data[4:8]))
		}
		return info, true
	}
	if version == 43 {
		info := tiffInfo{little: little, big: true, countBytes: 8, offsetBytes: 8, entrySize: 20, headerSize: 16}
		if len(data) >= info.headerSize {
			info.first = order.Uint64(data[8:16])
		}
		return info, true
	}
	return tiffInfo{}, false
}

func tiffOrder(info tiffInfo) binary.ByteOrder {
	if info.little {
		return binary.LittleEndian
	}
	return binary.BigEndian
}
func tiffTypeSize(t uint16) uint64 {
	switch t {
	case 1, 2, 6, 7:
		return 1
	case 3, 8:
		return 2
	case 4, 9:
		return 4
	case 5, 10, 12:
		return 8
	case 11:
		return 4
	default:
		return 1
	}
}

type tiffEntry struct {
	tag         uint16
	typ         uint16
	count       uint64
	value       []byte
	valueOffset uint64
	inline      bool
	entryOffset int
}

func tiffEntryPointer(info tiffInfo, entry tiffEntry) (uint64, bool) {
	ord := tiffOrder(info)
	if info.big {
		if len(entry.value) < 8 {
			return 0, false
		}
		return ord.Uint64(entry.value[:8]), true
	}
	if len(entry.value) < 4 {
		return 0, false
	}
	return uint64(ord.Uint32(entry.value[:4])), true
}

func isTIFFPointerTag(tag uint16) bool {
	return tag == 34665 || tag == 34853 || tag == 40965
}

func isTIFFSubIFDTag(tag uint16) bool {
	return tag == 34665 || tag == 34853
}

func tiffIFDBlockEnd(data []byte, info tiffInfo, offset uint64) uint64 {
	if offset >= uint64(len(data)) || offset+uint64(info.countBytes) > uint64(len(data)) {
		return offset
	}
	ord := tiffOrder(info)
	var count uint64
	if info.big {
		count = ord.Uint64(data[offset : offset+8])
	} else {
		count = uint64(ord.Uint16(data[offset : offset+2]))
	}
	base := offset + uint64(info.countBytes)
	if count > (^uint64(0)-base)/uint64(info.entrySize) {
		return uint64(len(data))
	}
	end := base + count*uint64(info.entrySize)
	if end > ^uint64(0)-uint64(info.offsetBytes) {
		return uint64(len(data))
	}
	end += uint64(info.offsetBytes)
	if end > uint64(len(data)) {
		return uint64(len(data))
	}
	return end
}

func tiffSubIFDHasMarkers(data []byte, info tiffInfo, offset uint64) bool {
	if offset == 0 {
		return false
	}
	entries, _, valid := readTIFFIFD(data, info, offset)
	if !valid {
		return false
	}
	end := tiffIFDBlockEnd(data, info, offset)
	if end > uint64(len(data)) {
		end = uint64(len(data))
	}
	if offset < end && len(containsAny(data[offset:end], append(aiMetaHints, c2paMarkers...))) > 0 {
		return true
	}
	for _, entry := range entries {
		if len(containsAny(tiffEntryPayload(entry), append(aiMetaHints, c2paMarkers...))) > 0 {
			return true
		}
	}
	return false
}

type tiffIFDRecord struct {
	entries  []tiffEntry
	next     uint64
	blockEnd uint64
}

// collectTIFFIFDs walks the IFD graph once and records the original byte
// extent of every reachable directory. Keeping the original extents is what
// lets stripTIFF compact dropped entries in place without moving image data
// referenced by StripOffsets/TileOffsets.
func collectTIFFIFDs(data []byte, info tiffInfo) map[uint64]tiffIFDRecord {
	ifds := map[uint64]tiffIFDRecord{}
	todo := []uint64{info.first}
	for len(todo) > 0 && len(ifds) < 4096 {
		off := todo[len(todo)-1]
		todo = todo[:len(todo)-1]
		if off == 0 || off >= uint64(len(data)) {
			continue
		}
		if _, seen := ifds[off]; seen {
			continue
		}
		entries, next, valid := readTIFFIFD(data, info, off)
		if !valid {
			continue
		}
		record := tiffIFDRecord{entries: entries, next: next, blockEnd: tiffIFDBlockEnd(data, info, off)}
		if record.blockEnd < off {
			record.blockEnd = uint64(len(data))
		}
		if record.blockEnd > uint64(len(data)) {
			record.blockEnd = uint64(len(data))
		}
		ifds[off] = record
		if next != 0 {
			todo = append(todo, next)
		}
		for _, entry := range entries {
			if isTIFFPointerTag(entry.tag) {
				if ptr, ok := tiffEntryPointer(info, entry); ok && ptr != 0 {
					todo = append(todo, ptr)
				}
			}
		}
	}
	return ifds
}

func tiffEntryByteSize(entry tiffEntry) (uint64, bool) {
	size := tiffTypeSize(entry.typ)
	if entry.count != 0 && size > ^uint64(0)/entry.count {
		return 0, false
	}
	return entry.count * size, true
}

// tiffEntryPayload returns only the declared value bytes. Inline TIFF fields
// are padded to four/eight bytes, and scanning that padding can create false
// marker hits that Python's reference parser does not report.
func tiffEntryPayload(entry tiffEntry) []byte {
	size, ok := tiffEntryByteSize(entry)
	if !ok || size == 0 || len(entry.value) == 0 {
		return nil
	}
	if size < uint64(len(entry.value)) {
		return entry.value[:int(size)]
	}
	return entry.value
}

func tiffIFDOffsets(ifds map[uint64]tiffIFDRecord) []uint64 {
	offsets := make([]uint64, 0, len(ifds))
	for off := range ifds {
		offsets = append(offsets, off)
	}
	sort.Slice(offsets, func(i, j int) bool { return offsets[i] < offsets[j] })
	return offsets
}

func appendTIFFOffset(dst []byte, info tiffInfo, value uint64) []byte {
	ord := tiffOrder(info)
	if info.big {
		var raw [8]byte
		ord.PutUint64(raw[:], value)
		return append(dst, raw[:]...)
	}
	var raw [4]byte
	ord.PutUint32(raw[:], uint32(value))
	return append(dst, raw[:]...)
}

func tiffRangeCovered(ranges [][2]uint64, start, end uint64) bool {
	for _, current := range ranges {
		if current[0] <= start && end <= current[1] {
			return true
		}
	}
	return false
}

func collectTIFFDroppedIFD(data []byte, info tiffInfo, ifds map[uint64]tiffIFDRecord, offset uint64, dropRanges, dropIFDRanges *[][2]uint64, seen map[uint64]bool) {
	if offset == 0 || seen[offset] {
		return
	}
	record, ok := ifds[offset]
	if !ok {
		return
	}
	seen[offset] = true
	*dropIFDRanges = append(*dropIFDRanges, [2]uint64{offset, record.blockEnd})
	for _, entry := range record.entries {
		if isTIFFSubIFDTag(entry.tag) {
			if ptr, pointerOK := tiffEntryPointer(info, entry); pointerOK {
				collectTIFFDroppedIFD(data, info, ifds, ptr, dropRanges, dropIFDRanges, seen)
			}
			continue
		}
		if entry.inline || entry.valueOffset == 0 || len(tiffEntryPayload(entry)) == 0 {
			continue
		}
		valueEnd := entry.valueOffset + uint64(len(tiffEntryPayload(entry)))
		if valueEnd >= entry.valueOffset && valueEnd <= uint64(len(data)) {
			*dropRanges = append(*dropRanges, [2]uint64{entry.valueOffset, valueEnd})
		}
	}
}

func zeroTIFFIFD(data []byte, info tiffInfo, offset uint64, out []byte, zeroRange func(uint64, uint64), seen map[uint64]bool) {
	if offset == 0 || seen[offset] {
		return
	}
	seen[offset] = true
	entries, next, valid := readTIFFIFD(data, info, offset)
	if !valid {
		return
	}
	end := tiffIFDBlockEnd(data, info, offset)
	zeroRange(offset, end)
	for _, entry := range entries {
		if isTIFFPointerTag(entry.tag) {
			if ptr, ok := tiffEntryPointer(info, entry); ok {
				zeroTIFFIFD(data, info, ptr, out, zeroRange, seen)
			}
		} else if !entry.inline && entry.valueOffset > 0 && len(entry.value) > 0 {
			zeroRange(entry.valueOffset, entry.valueOffset+uint64(len(entry.value)))
		}
	}
	if next != 0 {
		zeroTIFFIFD(data, info, next, out, zeroRange, seen)
	}
}

func readTIFFIFD(data []byte, info tiffInfo, offset uint64) ([]tiffEntry, uint64, bool) {
	if offset > uint64(len(data)) || offset+uint64(info.countBytes) > uint64(len(data)) {
		return nil, 0, false
	}
	ord := tiffOrder(info)
	var count uint64
	if info.big {
		count = ord.Uint64(data[offset : offset+8])
	} else {
		count = uint64(ord.Uint16(data[offset : offset+2]))
	}
	declaredCount := count
	if count > 4096 {
		count = 4096
	}
	entries := make([]tiffEntry, 0, int(count))
	base := offset + uint64(info.countBytes)
	for i := uint64(0); i < count; i++ {
		eoff := base + i*uint64(info.entrySize)
		if eoff+uint64(info.entrySize) > uint64(len(data)) {
			break
		}
		e := int(eoff)
		tag := ord.Uint16(data[e : e+2])
		typ := ord.Uint16(data[e+2 : e+4])
		var num uint64
		if info.big {
			num = ord.Uint64(data[e+4 : e+12])
		} else {
			num = uint64(ord.Uint32(data[e+4 : e+8]))
		}
		valueSize := num * tiffTypeSize(typ)
		if num != 0 && valueSize/num != tiffTypeSize(typ) {
			valueSize = uint64(len(data) + 1)
		}
		valueField := e + 8
		fieldSize := 4
		if info.big {
			valueField = e + 12
			fieldSize = 8
		}
		entry := tiffEntry{tag: tag, typ: typ, count: num, entryOffset: e}
		if valueSize <= uint64(fieldSize) {
			entry.value = append([]byte(nil), data[valueField:valueField+fieldSize]...)
			entry.inline = true
		} else {
			if info.big {
				if valueField+8 > len(data) {
					continue
				}
				entry.valueOffset = ord.Uint64(data[valueField : valueField+8])
			} else {
				entry.valueOffset = uint64(ord.Uint32(data[valueField : valueField+4]))
			}
			if entry.valueOffset <= uint64(len(data)) && valueSize <= uint64(len(data))-entry.valueOffset {
				entry.value = append([]byte(nil), data[entry.valueOffset:entry.valueOffset+valueSize]...)
			}
		}
		entries = append(entries, entry)
	}
	if declaredCount > (^uint64(0)-base)/uint64(info.entrySize) {
		return entries, 0, true
	}
	nextPos := base + declaredCount*uint64(info.entrySize)
	if nextPos+uint64(info.offsetBytes) > uint64(len(data)) {
		return entries, 0, true
	}
	var next uint64
	if info.big {
		next = ord.Uint64(data[nextPos : nextPos+8])
	} else {
		next = uint64(ord.Uint32(data[nextPos : nextPos+4]))
	}
	return entries, next, true
}

func inspectTIFF(data []byte) (bool, bool, []string) {
	info, ok := tiffLayout(data)
	if !ok {
		return false, false, []string{"not a TIFF"}
	}
	if info.first == 0 || info.first > uint64(len(data)) || uint64(info.countBytes) > uint64(len(data))-info.first {
		return false, false, []string{"TIFF with no image file directories"}
	}
	findings := []string{}
	var c2pa, ai bool
	queue := []uint64{info.first}
	seen := map[uint64]bool{}
	for len(queue) > 0 && len(seen) < 4096 {
		off := queue[0]
		queue = queue[1:]
		if off == 0 || seen[off] {
			continue
		}
		seen[off] = true
		entries, next, valid := readTIFFIFD(data, info, off)
		if !valid {
			continue
		}
		for _, e := range entries {
			hits := containsAny(tiffEntryPayload(e), append(aiMetaHints, c2paMarkers...))
			if len(hits) > 0 {
				ai = true
				if isC2PAHit(hits) {
					c2pa = true
				}
				findings = append(findings, fmt.Sprintf("TIFF tag %d: %s", e.tag, strings.Join(hits[:minInt(6, len(hits))], ", ")))
			}
			if name, known := tiffMetadataTags[e.tag]; known {
				label := "tag"
				if e.tag == 34665 || e.tag == 34853 || e.tag == 40965 {
					label = "sub-IFD"
				}
				findings = append(findings, fmt.Sprintf("TIFF %s %d (%s) present", label, e.tag, name))
			}
			if isTIFFPointerTag(e.tag) {
				if ptr, ok := tiffEntryPointer(info, e); ok && ptr > 0 {
					queue = append(queue, ptr)
				}
			}
		}
		if next != 0 {
			queue = append(queue, next)
		}
	}
	whole := containsAny(data, c2paMarkers)
	if len(whole) > 0 && !c2pa {
		c2pa = true
		ai = true
		if len(whole) > 6 {
			whole = whole[:6]
		}
		findings = append(findings, "byte-scan C2PA markers: "+strings.Join(whole[:minInt(6, len(whole))], ", "))
	}
	if len(findings) == 0 {
		findings = append(findings, "no TIFF metadata tags found")
	}
	return c2pa, ai || c2pa, findings
}

func stripTIFF(data []byte, stripAll bool) ([]byte, []string) {
	info, ok := tiffLayout(data)
	if !ok {
		return data, []string{"not TIFF"}
	}
	ifds := collectTIFFIFDs(data, info)
	if len(ifds) == 0 {
		return data, []string{"not a valid TIFF (no image file directories)"}
	}
	actions := []string{}
	kept := make(map[uint64][]tiffEntry, len(ifds))
	dropRanges := [][2]uint64{}
	dropIFDRanges := [][2]uint64{}
	for _, off := range tiffIFDOffsets(ifds) {
		record := ifds[off]
		keepHere := make([]tiffEntry, 0, len(record.entries))
		for _, entry := range record.entries {
			payload := tiffEntryPayload(entry)
			markerHit := len(containsAny(payload, append(aiMetaHints, c2paMarkers...))) > 0
			if isTIFFSubIFDTag(entry.tag) {
				if ptr, pointerOK := tiffEntryPointer(info, entry); pointerOK {
					if sub, exists := ifds[ptr]; exists {
						subEnd := sub.blockEnd
						if subEnd > uint64(len(data)) {
							subEnd = uint64(len(data))
						}
						if ptr < subEnd {
							markerHit = markerHit || len(containsAny(data[ptr:subEnd], append(aiMetaHints, c2paMarkers...))) > 0
						}
						markerHit = markerHit || tiffSubIFDHasMarkers(data, info, ptr)
					}
				}
			}
			_, known := tiffMetadataTags[entry.tag]
			drop := known && (stripAll || markerHit)
			if !known && markerHit && !tiffStructuralTags[entry.tag] {
				drop = true
			}
			if !drop {
				keepHere = append(keepHere, entry)
				continue
			}
			name, knownName := tiffMetadataTags[entry.tag]
			if knownName {
				name = fmt.Sprintf("%d (%s)", entry.tag, name)
			} else {
				name = fmt.Sprintf("%d (AI markers)", entry.tag)
			}
			actions = append(actions, "drop TIFF tag "+name)
			if isTIFFSubIFDTag(entry.tag) {
				if ptr, pointerOK := tiffEntryPointer(info, entry); pointerOK {
					collectTIFFDroppedIFD(data, info, ifds, ptr, &dropRanges, &dropIFDRanges, map[uint64]bool{})
				}
			} else if !entry.inline && entry.valueOffset > 0 && len(tiffEntryPayload(entry)) > 0 {
				end := entry.valueOffset + uint64(len(tiffEntryPayload(entry)))
				if end >= entry.valueOffset && end <= uint64(len(data)) {
					dropRanges = append(dropRanges, [2]uint64{entry.valueOffset, end})
				}
			}
		}
		kept[off] = keepHere
	}

	// Directories and value payloads still reachable from kept entries are
	// protected from zeroing. Metadata values can be shared by multiple tags.
	reachable := map[uint64]bool{}
	var markReachable func(uint64)
	markReachable = func(off uint64) {
		if reachable[off] {
			return
		}
		record, exists := ifds[off]
		if !exists {
			return
		}
		reachable[off] = true
		for _, entry := range kept[off] {
			if isTIFFPointerTag(entry.tag) {
				if ptr, pointerOK := tiffEntryPointer(info, entry); pointerOK {
					markReachable(ptr)
				}
			}
		}
		if record.next != 0 {
			markReachable(record.next)
		}
	}
	markReachable(info.first)
	referenced := [][2]uint64{}
	for _, off := range tiffIFDOffsets(ifds) {
		if !reachable[off] {
			continue
		}
		for _, entry := range kept[off] {
			if !entry.inline && entry.valueOffset > 0 && len(tiffEntryPayload(entry)) > 0 {
				end := entry.valueOffset + uint64(len(tiffEntryPayload(entry)))
				if end >= entry.valueOffset && end <= uint64(len(data)) {
					referenced = append(referenced, [2]uint64{entry.valueOffset, end})
				}
			}
			if isTIFFPointerTag(entry.tag) {
				if ptr, pointerOK := tiffEntryPointer(info, entry); pointerOK {
					if sub, exists := ifds[ptr]; exists {
						referenced = append(referenced, [2]uint64{ptr, sub.blockEnd})
					}
				}
			}
		}
	}
	zeroRanges := [][2]uint64{}
	for _, current := range dropRanges {
		if !tiffRangeCovered(referenced, current[0], current[1]) {
			zeroRanges = append(zeroRanges, current)
		}
	}
	for _, current := range dropIFDRanges {
		if !tiffRangeCovered(referenced, current[0], current[1]) {
			zeroRanges = append(zeroRanges, current)
		}
	}

	out := append([]byte(nil), data...)
	ord := tiffOrder(info)
	for _, off := range tiffIFDOffsets(ifds) {
		record := ifds[off]
		block := make([]byte, 0, int(record.blockEnd-off))
		if info.big {
			var count [8]byte
			ord.PutUint64(count[:], uint64(len(kept[off])))
			block = append(block, count[:]...)
		} else {
			var count [2]byte
			ord.PutUint16(count[:], uint16(len(kept[off])))
			block = append(block, count[:]...)
		}
		for _, entry := range kept[off] {
			start := entry.entryOffset
			end := start + info.entrySize
			if start >= 0 && end <= len(data) {
				block = append(block, data[start:end]...)
			}
		}
		block = appendTIFFOffset(block, info, record.next)
		regionLen := record.blockEnd - off
		if regionLen > uint64(len(out))-off {
			regionLen = uint64(len(out)) - off
		}
		if uint64(len(block)) > regionLen {
			block = block[:int(regionLen)]
		}
		copy(out[off:off+regionLen], block)
		for i := uint64(len(block)); i < regionLen; i++ {
			out[off+i] = 0
		}
	}
	for _, current := range zeroRanges {
		start, end := current[0], current[1]
		if start >= uint64(len(out)) {
			continue
		}
		if end > uint64(len(out)) {
			end = uint64(len(out))
		}
		for i := start; i < end; i++ {
			out[i] = 0
		}
	}
	if len(actions) == 0 {
		actions = append(actions, "no TIFF metadata tags removed (already clean or none matched)")
	}
	return out, actions
}

func binaryPut16(dst []byte, value uint16, order binary.ByteOrder) {
	if len(dst) >= 2 {
		order.PutUint16(dst[:2], value)
	}
}

type bmffBox struct {
	typ     []byte
	payload []byte
	total   int
	header  int
	start   int
}

func parseBMFF(data []byte, start, end int) ([]bmffBox, int) {
	if end < 0 || end > len(data) {
		end = len(data)
	}
	boxes := []bmffBox{}
	pos := start
	for pos+8 <= end {
		size := int(binary.BigEndian.Uint32(data[pos : pos+4]))
		hdr := 8
		if size == 1 {
			if pos+16 > end {
				break
			}
			u := binary.BigEndian.Uint64(data[pos+8 : pos+16])
			if u > uint64(end-pos) {
				break
			}
			size = int(u)
			hdr = 16
		} else if size == 0 {
			size = end - pos
		}
		if size < hdr || pos+size > end {
			break
		}
		boxes = append(boxes, bmffBox{append([]byte(nil), data[pos+4:pos+8]...), data[pos+hdr : pos+size], size, hdr, pos})
		pos += size
	}
	return boxes, pos
}

func buildBMFFBox(typ, payload []byte, originalHeader int) []byte {
	hdr := originalHeader
	if hdr != 16 && uint64(len(payload))+8 > uint64(^uint32(0)) {
		hdr = 16
	}
	size := hdr + len(payload)
	out := make([]byte, size)
	if hdr == 16 {
		binary.BigEndian.PutUint32(out[:4], 1)
		binary.BigEndian.PutUint64(out[8:16], uint64(size))
	} else {
		binary.BigEndian.PutUint32(out[:4], uint32(size))
	}
	copy(out[4:8], typ)
	copy(out[hdr:], payload)
	return out
}

func freeBMFFBox(size, header int) []byte {
	if size < header || size < 8 {
		return nil
	}
	payload := make([]byte, size-header)
	return buildBMFFBox([]byte("free"), payload, header)
}

func isC2PABMFFUUID(payload []byte) bool {
	return len(payload) >= 16 && (bytes.Equal(payload[:16], c2paBMFFUUID) ||
		len(payload) >= 20 && bytes.Equal(payload[4:20], c2paBMFFUUID))
}

func containsC2PABMFFUUID(data []byte) bool {
	for pos := 0; pos+4 <= len(data); {
		offset := bytes.Index(data[pos:], []byte("uuid"))
		if offset < 0 {
			return false
		}
		offset += pos
		payload := data[offset+4:]
		if isC2PABMFFUUID(payload) {
			return true
		}
		pos = offset + 4
	}
	return false
}

func inspectISOBMFF(data []byte, format string) (bool, bool, []string) {
	boxes, end := parseBMFF(data, 0, len(data))
	if len(boxes) == 0 {
		findings := []string{}
		if whole := containsAny(data, c2paMarkers); len(whole) > 0 {
			findings = append(findings, "byte-scan C2PA markers: "+strings.Join(whole[:minInt(6, len(whole))], ", "))
		} else if containsC2PABMFFUUID(data) {
			findings = append(findings, "byte-scan C2PA BMFF content-provenance user type")
		}
		findings = append(findings, "not a valid "+strings.ToUpper(format)+" (no ISOBMFF boxes found)")
		hasC2PA := len(findings) > 1
		return hasC2PA, hasC2PA, findings
	}
	findings := []string{}
	var c2pa, ai bool
	namePrefix := strings.ToUpper(format)
	for _, b := range boxes {
		name := string(b.typ)
		low := strings.ToLower(name)
		if b.typEqual("jumb") || b.typEqual("c2pa") || strings.HasPrefix(low, "c2") {
			c2pa = true
			findings = append(findings, fmt.Sprintf("%s top-level box %s (C2PA/JUMBF manifest)", namePrefix, name))
		} else if b.typEqual("uuid") {
			if bytes.HasPrefix(b.payload, xmpUUID) {
				ai = true
				xmpHits := containsAny(b.payload[16:], append(aiMetaHints, c2paMarkers...))
				if len(xmpHits) > 0 {
					findings = append(findings, fmt.Sprintf("%s XMP uuid box: %s", namePrefix, strings.Join(xmpHits[:minInt(8, len(xmpHits))], ", ")))
				} else {
					findings = append(findings, fmt.Sprintf("%s XMP uuid box", namePrefix))
				}
				if anyHit(xmpHits, "c2pa", "contentcredentials", "jumb", "contentauth") {
					c2pa = true
				}
			} else if isC2PABMFFUUID(b.payload) {
				c2pa = true
				findings = append(findings, fmt.Sprintf("%s uuid box (C2PA content-provenance manifest, user type d8fec3d6...)", namePrefix))
			} else if hits := containsAny(b.payload, append(aiMetaHints, c2paMarkers...)); len(hits) > 0 {
				ai = true
				findings = append(findings, fmt.Sprintf("%s uuid box: %s", namePrefix, strings.Join(hits[:minInt(8, len(hits))], ", ")))
				if anyHit(hits, "c2pa", "contentcredentials", "jumb") {
					c2pa = true
				}
			}
		} else if b.typEqual("meta") && len(b.payload) >= 4 {
			metaSub, _ := parseBMFF(b.payload, 4, len(b.payload))
			for _, s := range metaSub {
				sName := string(s.typ)
				sLow := strings.ToLower(sName)
				if s.typEqual("jumb") || s.typEqual("c2pa") || strings.HasPrefix(sLow, "c2") {
					c2pa = true
					findings = append(findings, fmt.Sprintf("%s meta sub-box %s (C2PA/JUMBF container)", namePrefix, sName))
					continue
				}
				if s.typEqual("uuid") {
					if bytes.HasPrefix(s.payload, xmpUUID) {
						ai = true
						hits := containsAny(s.payload[16:], append(aiMetaHints, c2paMarkers...))
						if len(hits) > 0 {
							findings = append(findings, fmt.Sprintf("%s meta XMP uuid: %s", namePrefix, strings.Join(hits[:minInt(8, len(hits))], ", ")))
						} else {
							findings = append(findings, fmt.Sprintf("%s meta XMP uuid box", namePrefix))
						}
						if anyHit(hits, "c2pa", "contentcredentials", "jumb") {
							c2pa = true
						}
					} else if isC2PABMFFUUID(s.payload) {
						c2pa = true
						findings = append(findings, fmt.Sprintf("%s meta uuid box (C2PA content-provenance manifest)", namePrefix))
					} else if hits := containsAny(s.payload, append(aiMetaHints, c2paMarkers...)); len(hits) > 0 {
						ai = true
						findings = append(findings, fmt.Sprintf("%s meta uuid: %s", namePrefix, strings.Join(hits[:minInt(8, len(hits))], ", ")))
					}
					continue
				}
				if s.typEqual("iinf") || s.typEqual("infe") || s.typEqual("iref") || s.typEqual("iloc") || s.typEqual("xml ") || s.typEqual("bxml") {
					hits := containsAny(s.payload, append(aiMetaHints, c2paMarkers...))
					if len(hits) == 0 {
						continue
					}
					ai = true
					if anyHit(hits, "c2pa", "contentcredentials", "jumb") {
						c2pa = true
					}
					findings = append(findings, fmt.Sprintf("%s meta/%s: %s", namePrefix, sName, strings.Join(hits[:minInt(8, len(hits))], ", ")))
				}
			}
		}
	}
	if !c2pa {
		if whole := containsAny(data, c2paMarkers); len(whole) > 0 {
			c2pa = true
			findings = append(findings, "byte-scan C2PA markers: "+strings.Join(whole[:minInt(6, len(whole))], ", "))
		} else if containsC2PABMFFUUID(data) {
			c2pa = true
			findings = append(findings, "byte-scan C2PA BMFF content-provenance user type")
		}
	}
	_ = end
	return c2pa, ai || c2pa, findings
}

func anyHit(hits []string, wanted ...string) bool {
	for _, hit := range hits {
		for _, value := range wanted {
			if strings.EqualFold(hit, value) {
				return true
			}
		}
	}
	return false
}

func (b bmffBox) typEqual(s string) bool { return string(b.typ) == s }

func stripISOBMFF(data []byte, format string, stripAll bool) ([]byte, []string, error) {
	boxes, end := parseBMFF(data, 0, len(data))
	if len(boxes) == 0 {
		return data, nil, fmt.Errorf("not a valid %s (no ISOBMFF boxes found)", strings.ToUpper(format))
	}
	actions := []string{}
	out := []byte{}
	var cleanMeta func([]byte) []byte
	cleanMeta = func(payload []byte) []byte {
		if len(payload) < 4 {
			return payload
		}
		prefix := payload[:4]
		subs, scanned := parseBMFF(payload, 4, len(payload))
		clean := append([]byte(nil), prefix...)
		for _, s := range subs {
			name := string(s.typ)
			drop := false
			reason := ""
			if s.typEqual("jumb") || s.typEqual("c2pa") || strings.HasPrefix(strings.ToLower(name), "c2") {
				drop = true
				reason = "C2PA/JUMBF"
			}
			if s.typEqual("uuid") {
				switch {
				case bytes.HasPrefix(s.payload, xmpUUID):
					drop, reason = true, "XMP metadata"
				case isC2PABMFFUUID(s.payload):
					drop, reason = true, "C2PA content-provenance manifest"
				case stripAll || len(containsAny(s.payload, append(aiMetaHints, c2paMarkers...))) > 0:
					drop, reason = true, "UUID metadata"
				}
			}
			if (s.typEqual("xml ") || s.typEqual("bxml")) && (stripAll || len(containsAny(s.payload, append(aiMetaHints, c2paMarkers...))) > 0) {
				drop, reason = true, "XML metadata"
			}
			if drop {
				actions = append(actions, fmt.Sprintf("drop meta sub-box %s (%s)", name, reason))
				clean = append(clean, freeBMFFBox(s.total, s.header)...)
			} else {
				clean = append(clean, buildBMFFBox(s.typ, s.payload, s.header)...)
			}
		}
		if scanned < len(payload) {
			clean = append(clean, payload[scanned:]...)
		}
		return clean
	}
	for _, b := range boxes {
		name := string(b.typ)
		drop := false
		reason := ""
		if b.typEqual("jumb") || b.typEqual("c2pa") || strings.HasPrefix(strings.ToLower(name), "c2") {
			drop = true
			reason = "C2PA/JUMBF"
		}
		if b.typEqual("uuid") {
			switch {
			case bytes.HasPrefix(b.payload, xmpUUID):
				drop, reason = true, "XMP metadata"
			case isC2PABMFFUUID(b.payload):
				drop, reason = true, "C2PA content-provenance manifest"
			case stripAll || len(containsAny(b.payload, append(aiMetaHints, c2paMarkers...))) > 0:
				drop, reason = true, "UUID metadata"
			}
		}
		if b.typEqual("meta") {
			newPayload := cleanMeta(b.payload)
			out = append(out, buildBMFFBox(b.typ, newPayload, b.header)...)
			continue
		}
		if drop {
			actions = append(actions, fmt.Sprintf("drop top-level %s box (%s)", name, reason))
			out = append(out, freeBMFFBox(b.total, b.header)...)
		} else {
			out = append(out, buildBMFFBox(b.typ, b.payload, b.header)...)
		}
	}
	if end < len(data) {
		out = append(out, data[end:]...)
		if len(data)-end >= 8 {
			actions = append(actions, fmt.Sprintf("kept %d bytes of truncated tail (file truncated)", len(data)-end))
		}
	}
	if len(actions) == 0 {
		actions = append(actions, "no "+strings.ToUpper(format)+" metadata boxes removed (already clean or none matched)")
	}
	return out, actions, nil
}
